<a href="https://colab.research.google.com/github/suuizee/dap-2024/blob/main/rep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [11]:
import numpy as np
np.version.version

'1.26.4'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [1]:
import numpy as np
array = np.random.randint(1, 100, (10, 10))
print("\nСозданный массив: \n\n", array)
print("\nМинимальное значение:", array.min())
print("Максимальное значение:", array.max())


Созданный массив: 

 [[57 28 13 46 57 12 67 37 74 86]
 [76 13 87  5 50 42 44 17 41 68]
 [19 58 14 82 26 17 78 26 99  2]
 [87  3 51 12 89 17 75 14 66 87]
 [97 31 61 70 59 68  8 27 50  3]
 [61 78 94 23 91 52 35 15 91 39]
 [14 13 38 36 55 50 58 62 67 92]
 [28  2 77 60 13 82 18 77 86 63]
 [46 24 77 47 61 68 14 60 84 10]
 [13 25 72 38 33 57 31 36 39 21]]

Минимальное значение: 2
Максимальное значение: 99


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [10]:
import numpy as np
matrix = np.zeros((8,8))
matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1
print("Матрица 8х8 в шахматном порядке: \n", matrix)

Матрица 8х8 в шахматном порядке: 
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [9]:
import numpy as np
x = np.arange(11)
print("Исходный массив:\n", x)
x[(x > 3) & (x < 8)] *= -1
print("\nИзмененный массив:\n", x)

Исходный массив:
 [ 0  1  2  3  4  5  6  7  8  9 10]

Измененный массив:
 [ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [8]:
import numpy as np
z = np.random.rand(5, 10)
print("Матрица: \n", z)
means = np.mean(z, axis=1, keepdims=True)
z[:, :9] -= means
print("\nСреднее значение:\n", means)
print("\nИзмененная матрица:\n", z)

Матрица: 
 [[0.06918355 0.51134444 0.43014902 0.05428476 0.62187003 0.52537216
  0.75201293 0.4125177  0.89116276 0.88223887]
 [0.98558987 0.44183375 0.59022005 0.25255584 0.88202873 0.10319399
  0.39762853 0.98516608 0.326175   0.41826283]
 [0.39680835 0.78668751 0.59442083 0.41833609 0.45756823 0.97371392
  0.78649234 0.26530443 0.29186427 0.46347221]
 [0.42283748 0.12661135 0.48239362 0.13801445 0.31618534 0.82317522
  0.58082667 0.70677558 0.0103794  0.54226729]
 [0.45918999 0.76929465 0.39505428 0.98292554 0.22702764 0.27139699
  0.66403054 0.33702751 0.08822533 0.28632324]]

Среднее значение:
 [[0.51501362]
 [0.53826547]
 [0.54346682]
 [0.41494664]
 [0.44804957]]

Измененная матрица:
 [[-0.44583007 -0.00366918 -0.08486461 -0.46072886  0.10685641  0.01035854
   0.23699931 -0.10249592  0.37614914  0.88223887]
 [ 0.4473244  -0.09643171  0.05195458 -0.28570963  0.34376327 -0.43507148
  -0.14063694  0.44690061 -0.21209047  0.41826283]
 [-0.14665847  0.24322069  0.05095401 -0.12513073 

5. Поменяйте 1 и 2 строки матрицы

In [7]:
import numpy as np
z = np.arange(25).reshape(5,5)
print("Матрица:\n", z)
z[[1, 2]] = z[[2, 1]]
print("\nИзмененная матрица:\n", z)

Матрица:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Измененная матрица:
 [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [6]:
import numpy as np
z = np.random.random((10, 2))
print("Декартова система координат:\n", z)
x = z[:, 0]
y = z[:, 1]
r = np.sqrt(x ** 2 + y ** 2)
phi = np.arctan2(y, x)
pz = np.column_stack((r, phi))
print("\nПолярные координаты:\n", pz)

Декартова система координат:
 [[0.72690354 0.7019418 ]
 [0.16510831 0.16365664]
 [0.47292758 0.44710649]
 [0.33983323 0.92482618]
 [0.37736802 0.7776974 ]
 [0.55709729 0.87997892]
 [0.9384045  0.04557398]
 [0.69654473 0.89845403]
 [0.37157113 0.59642492]
 [0.23796389 0.45235851]]

Полярные координаты:
 [[1.0105004  0.76793007]
 [0.23247419 0.78098267]
 [0.65081849 0.75734018]
 [0.9852868  1.21865563]
 [0.8644188  1.11902823]
 [1.04149906 1.00640757]
 [0.93951051 0.04852726]
 [1.13683517 0.91131741]
 [0.70270035 1.01363843]
 [0.51113114 1.08652535]]


7. Заменить максимальный элемент массива на ноль

In [5]:
import numpy as np
z = np.random.random(10)
print("Массив:\n", z)
max = np.argmax(z)
print("\nИндекс максимального элемента:", max)
z[max] = 0
print("\nИзмененный массив:\n", z)

Массив:
 [0.49463739 0.02823667 0.04487109 0.34076767 0.90665053 0.31055066
 0.29170958 0.37364844 0.64364174 0.22395348]

Индекс максимального элемента: 4

Измененный массив:
 [0.49463739 0.02823667 0.04487109 0.34076767 0.         0.31055066
 0.29170958 0.37364844 0.64364174 0.22395348]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [4]:
import numpy as np
z = np.ones(10)
i = np.random.randint(0,len(z),20)
print("Массив:\n", z)
print("\nМассив индексов:\n", i)
unique = np.unique(i)
z[unique] += 1
print("\nИзмененный массив:\n", z)

Массив:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Массив индексов:
 [3 3 1 0 6 9 3 2 2 6 0 3 8 8 2 3 1 2 1 7]

Измененный массив:
 [2. 2. 2. 2. 1. 1. 2. 2. 2. 2.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [3]:
import numpy as np
z = np.array([1,2,3,4,5])
print("Вектор:\n", z)
x = np.zeros(len(z) + (len(z) - 1) * 3)
x[::4] = z
print("\nНовый вектор:\n", x)

Вектор:
 [1 2 3 4 5]

Новый вектор:
 [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


10. Найти ближайшее к заданному значению число в заданном массиве

In [2]:
import numpy as np
z = np.arange(100)
v = np.random.uniform(0,100)
print("Массив:\n", z)
print("\nЗаданное значение:", v)
x = np.fabs(z - v).argmin()
y = z[x]
print("\nБлижайшее значение для", v, "=", y)

Массив:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Заданное значение: 28.528998596310206

Ближайшее значение для 28.528998596310206 = 29
